### ISSUE TITLE
Simulator build failure in XCode 3.2.4 with iOS4.1

### ISSUE THREAD

**Issue by dav** [neror/CA360#1]
Runs fine on my iPhone4 device, but when trying to build in the simulator there is this error in CA360_Prefix.pch line 59:

Expected function body after function declarator.

This is the line:

CG_EXTERN void CGPDFContextAddDocumentMetadata(CGContextRef context,
  CFDataRef metadata) CG_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_0);

Not sure what's up, the code looks fine.

**Comment by neror** [comment]
It's a bug with the LLVM compiler in the 4.1 SDK. I just pushed up the fix to the project. It should be fine now.

If it's still not working after you pull, you can change the compiler to GCC 4.2 in the target settings. That will fix it as well.
